create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  phone text not null,
  email text not null,
  event_type text not null,
  message text not null,
  notification_status text not null default 'pending',
  notification_error text
);

alter table public.leads enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'leads_notification_status_check'
  ) then
    alter table public.leads
      add constraint leads_notification_status_check
      check (notification_status in ('pending', 'sent', 'failed'));
  end if;
end $$;
